### ISSUE TITLE
full project

### ISSUE THREAD

**Issue by elpaxdota** [oxters168/ProjectDeagle#1]
Hello. You did great work. Thank you for that project. But can you release full project (with assets etc.) ? Because it's too hard to recover the gui from scripts.

**Comment by oxters168** [comment]
Thank you :) I shall see what I can do, but some assets I cannot upload since I bought them from the Asset Store.

**Comment by oxters168** [comment]
I have broken this project down into sub-repositories, and the biggest part is this one: https://github.com/oxters168/UnitySourceEngine

This is not the same as the full application, but I felt I needed to separate the parts that I can share from the parts that I cannot.
